import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {
  const [name, setName] = useState("");

  useEffect(() => {

    fetch("/api/hello")
      .then(response => response.json())
      .then(data => {
        console.log(data)
        setName(data.name)
      })
      .catch(error => {
        console.log(error)
      })

  }, [])

  return (
    <div >
      <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         
      <h1>Hello {name}</h1>
      <p><Link href="/citate">Citate</Link></p>
      <Link href="/paraphrase">Paraphrase</Link>

    </div>
  )
}
